### ISSUE TITLE
One or more errors occurred. (Sequence contains no elements)

### ISSUE THREAD

**Issue by gt4Rhys** [petrassurna/DotNetSiteSearch#1]
When using the "Publish with Descendants" option (when saving and publishing), the following error occurs:

SCREENSHOT: 

![Screenshot 2023-06-15 at 14 16 00](https://github.com/petrassurna/DotNetSiteSearch/assets/84839006/00ffa321-5f6b-48e2-b784-4672f72e15b7)

TEXT:

```
Received an error from the server
An error occurred
One or more errors occurred. (Sequence contains no elements)

Exception Details
System.AggregateException, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: One or more errors occurred. (Sequence contains no elements)
Stacktrace
at Umbraco.Cms.Infrastructure.Scoping.Scope.TryFinally(Action[] actions)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.Dispose()
   at Umbraco.Cms.Core.Services.ContentService.SaveAndPublishBranch(IContent document, Boolean force, Func`2 shouldPublish, Func`4 publishCultures, Int32 userId)
   at Umbraco.Cms.Core.Services.ContentService.SaveAndPublishBranch(IContent content, Boolean force, String culture, Int32 userId)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PublishBranchInternal(ContentItemSave contentItem, Boolean force, String cultureForInvariantErrors, Boolean& wasCancelled, String[]& successfulCultures)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSaveInternal[TVariant](ContentItemSave contentItem, Func`3 saveMethod, Func`2 mapToDisplay)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSave(ContentItemSave contentItem)
   at lambda_method749(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

This was tested using the V11 demo.

**Comment by petrassurna** [comment]
Thanks for listing the bug.
As the first user of any kind that I am aware of I am giving you a virtual hug :-)

I have stopped the crash and ensured indexing works.
Note for changes to appear in the search results Umbraco content must change when **Publishing with descendants**  but I guess that's obvious.

Also, use the new version 0.662 whose code base and file references are slightly different from the last version. You may need to redo the tutorial at [https://github.com/petrassurna/DotNetSiteSearch](https://github.com/petrassurna/DotNetSiteSearch)

Let me know if there are any other problems.

**Comment by gt4Rhys** [comment]
I may be the first, but I definitely won't be the last 😁!!

That fix works perfectly, thanks for sorting it out so quickly, it's really appreciated.
